---
start_date: &root_start_date '2020-01-20T00:00:00'
six_hourly_start_date: &six_hourly_start_date '2020-01-20T03:00:00'
stop_date: &root_stop_date '2020-01-20T21:00:00'
scheduler: slurm
front_depth: 2
cycles:
  - first icon:
      cycling:
        start_date: *root_start_date
        stop_date: *six_hourly_start_date
        period: PT3H  # Should be automatically computed for a single cycle => feedback
      tasks:
        - prepare_input:
            inputs:
              - tmp_data_pool:
                  port: data_pool
              - sst_ice_dir:
                  port: sst_ice_dir
              - ozone_dir:
                  port: ozone_dir
              - aero_kinne_dir:
                  port: aero_kine_dir
            outputs:
              - icon_link_input:
                  port: icon_input
        - icon:
            inputs:
              - icon_link_input:
                  port: link_content
              - ecrad_data:
                  port: ecrad_data
              - ECHAM6_CldOptProps:
                  port: cloud_opt_props
              - rrtmg_lw:
                  port: rrtmg_lw
              - icon_grid:
                  port: dynamics_grid_file
              - extpar_file:
                  port: extpar_file
              - analysis_file:
                  port: ifs2icon
            outputs:
              - first_restart:
                  port: latest_restart_file
              # output streams have to be specified even if unsued
              - stream_1:
                  port: output_streams
              - stream_2:
                  port: output_streams
  - icon six hourly:
      cycling:
        start_date: *six_hourly_start_date
        stop_date: *root_stop_date
        period: PT6H
      tasks:
        - prepare_input:
            inputs:
              - tmp_data_pool:
                  port: data_pool
              - sst_ice_dir:
                  port: sst_ice_dir
              - ozone_dir:
                  port: ozone_dir
              - aero_kinne_dir:
                  port: aero_kine_dir
            outputs:
              - icon_link_input:
                  port: icon_input
            wait_on:
              - icon:
                  when:
                    after: '2020-01-20T09:00:00'
                  target_cycle:
                    lag: '-PT12H'
        - icon:
            inputs:
              - icon_link_input:
                  port: link_content
              - ecrad_data:
                  port: ecrad_data
              - ECHAM6_CldOptProps:
                  port: cloud_opt_props
              - rrtmg_lw:
                  port: rrtmg_lw
              - icon_grid:
                  port: dynamics_grid_file
              - extpar_file:
                  port: extpar_file
              - analysis_file:
                  port: ifs2icon
              - first_restart:
                  port: restart_file
                  when:
                    at: *six_hourly_start_date
                  target_cycle:
                    lag: -PT3H
              - restart_six_hourly:
                  port: restart_file
                  when:
                    after: *six_hourly_start_date
                  target_cycle:
                    lag: -PT6H
            outputs:
              - restart_six_hourly:
                  port: latest_restart_file
              - stream_1:
                  port: output_streams
              - stream_2:
                  port: output_streams
        - post_proc:
            inputs:
              - stream_1:
                  port: stream
              - stream_2:
                  port: stream
tasks:
  - ROOT:
      account: cwd01
  - SIROCCO:
      walltime: 00:05:00
      # uenv: /capstor/store/cscs/userlab/cws01/uenvs/sirocco_v0.0.1.sqfs
      uenv: /capstor/store/cscs/userlab/cwd01/leclairm/uenvs/images/sirocco_v0.0.1_workgraph.sqfs
      # view: sirocco
      # venv: /user-tools/sirocco_venv/bin/activate
      
  - prepare_input:
      plugin: shell
      walltime: 00:05:00
      nodes: 1
      path: prepare_input.sh
      command: ./prepare_input.sh --pool={PORT::data_pool}  --sst-ice={PORT::sst_ice_dir} --ozone={PORT::ozone_dir} --aero-kine={PORT::aero_kine_dir} --icon-input={PORT::icon_input}
  - icon:
      plugin: icon
      uenv: icon/25.2:v3
      walltime: 01:00:00
      nodes: 2
      target: santis_gpu
      bin_cpu: /capstor/store/cscs/userlab/cwd01/leclairm/archive_icon_build/icon-nwp_cpu_25.2-v3/bin/icon
      bin_gpu: /capstor/store/cscs/userlab/cwd01/leclairm/archive_icon_build/icon-nwp_gpu_25.2-v3/bin/icon
      namelists:
        - ./ICON/icon_master.namelist
        - ./ICON/NAMELIST_DYAMOND_R02B06L120:
            radiation_nml:
              ecrad_isolver: 2  # 0 for cpu, 2 for gpu
            parallel_nml:
              num_io_procs: 1
  - post_proc:
      plugin: shell
      computer: santis
      path: post_proc.sh
      command: "uenv run /capstor/store/cscs/userlab/cws01/uenvs/climtools_25.2_v2.sqfs --view default -- post_proc.sh {PORT::stream}"
data:
  available:
     - icon_grid:
         path: /capstor/store/cscs/exclaim/excp01/ppothapa/data_from_santis/grids/MPI_grids/atmo/R02B06/icon_grid_0021_R02B06_G.nc
     - analysis_file:
         path: /capstor/store/cscs/exclaim/excp01/ppothapa/data_from_santis/grids/MPI_grids/atmo/R02B06/initial_conditions/ifs2icon_2020012000_0021_R02B06_G.nc
     - sst_ice_dir:
         path: /capstor/store/cscs/exclaim/excp01/ppothapa/data_from_santis/grids/MPI_grids/atmo/R02B06/sst_and_seaice/r0001
     - ozone_dir:
         path: /capstor/store/cscs/exclaim/excp01/ppothapa/data_from_santis/grids/MPI_grids/atmo/R02B06/ozone/r0001
     - aero_kinne_dir:
         path: /capstor/store/cscs/exclaim/excp01/ppothapa/data_from_santis/grids/MPI_grids/atmo/R02B06/aerosol_kinne/r0001
     - extpar_file:
         path: /capstor/store/cscs/exclaim/excp01/ppothapa/data_from_santis/grids/MPI_grids/atmo/R02B06/external_parameter/external_parameter_icon_0021_R02B06_G_tiles.nc
     - rrtmg_lw:
         path: /capstor/store/cscs/userlab/cwd01/leclairm/archive_icon_build/icon-nwp_cpu_25.2-v3/data/rrtmg_lw.nc
     - ECHAM6_CldOptProps:
         path: /capstor/store/cscs/userlab/cwd01/leclairm/archive_icon_build/icon-nwp_cpu_25.2-v3/data/ECHAM6_CldOptProps.nc
     - ecrad_data:
         path: /capstor/store/cscs/userlab/cwd01/leclairm/archive_icon_build/icon-nwp_cpu_25.2-v3/externals/ecrad/data
     - tmp_data_pool:
         path: /capstor/scratch/cscs/${USER}/DYAMOND_R02B06_input
  generated:
     - icon_link_input:
         path: 'icon_input'
     - stream_1: {}
     - stream_2: {}
     - first_restart: {}
     - restart_six_hourly: {}
